### PR TITLE
Retooling overall build with hugely improved site page

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by mikesamuel** [comment]
I'm not going to nitpick the maven parts.  I cloned your patch and `mvn test` seems to load fine.

The source changes seem fine.

Will merge.

**Comment by hazendaz** [comment]
Awesome!  Thanks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mikesamuel** [comment]
Available as http://search.maven.org/#artifactdetails%7Ccom.mikesamuel%7Cjson-sanitizer%7C1.2.0%7Cjar

**Comment by hazendaz** [comment]
Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
